---
- block:
    - name: Combine ip_address_list and vm_name_list list
      ansible.builtin.set_fact:
        dns_entry: "{{ ip_address_list | zip(vm_name_list) | map('join', ' ') | list }}"

    - name: Add DNS record(s) to Pihole (from project)
      ansible.builtin.lineinfile:
        backup: true
        path: /etc/pihole/custom.list
        line: "{{ dns_entry_item }}.{{ dns_suffix_list[0] }}"
        state: present
      loop: "{{ dns_entry }}"
      loop_control:
        loop_var: dns_entry_item
      notify:
        - Restart pihole-FTL
  when: ip_address_list is defined

- name: Add DNS record to Pihole
  ansible.builtin.lineinfile:
    backup: true
    path: /etc/pihole/custom.list
    regexp: "{{ customhost }}"
    line: "{{ customip }} {{ customhost }}"
    state: present
  notify:
    - Restart pihole-FTL
  when: customhost is defined
