---
- name: Create github key
  ansible.builtin.template:
    src: ssh-key-git.key.j2
    dest: /var/tmp/ssh-key-git.key
    mode: '0666'

- name: Pull down custom.list from git
  ansible.builtin.git:
    repo: 'git@github.com:eingram23/configs.git'
    dest: /var/tmp/configs
    key_file: /var/tmp/ssh-key-git.key
    accept_hostkey: true
