---
- name: Commit and push changes to custom.list
  environment:
    GIT_AUTHOR_NAME: eingram23
    GIT_AUTHOR_EMAIL: edward.ingram23@gmail.com
  lvrfrc87.git_acp.git_acp:
    path: /var/tmp/configs/pihole
    branch: main
    comment: Add host
    add: [ custom.list ]
    url: "git@github.com:eingram23/configs.git"
    ssh_params:
      key_file: /var/tmp/ssh-key-git.key

