---
- name: Remove DNS record(s) (from project)
  ansible.builtin.lineinfile:
    path: /var/tmp/configs/pihole/custom.list
    regexp: "{{ vm_name_list_item }}.{{ dns_suffix_list[0] }}"
    state: absent
  loop: "{{ vm_name_list }}"
  loop_control:
    loop_var: vm_name_list_item
  when: dns_suffix_list is defined

- name: Remove DNS record
  ansible.builtin.lineinfile:
    path: /var/tmp/configs/pihole/custom.list
    regexp: "{{ customhost }}"
    state: absent
  when: customhost is defined
