---
- name: Copy custom.list to pihole
  ansible.builtin.copy:
    src: /var/tmp/configs/pihole/custom.list
    dest: /opt/pihole/etc-pihole/custom.list
    mode: '0644'
  notify: Restart pihole container
