---
- name: Create github key
  ansible.builtin.template:
    src: ssh-key-git.key.j2
    dest: /var/tmp/ssh-key-git.key
    mode: '0400'
  delegate_to: localhost

- name: Pull down custom.list from git
  ansible.builtin.git:
    repo: 'git@github.com:eingram23/configs.git'
    dest: /var/tmp
    key_file: /var/tmp/ssh-key-git.key
    accept_hostkey: true
  delegate_to: localhost

- block:
    - name: Combine ip_address_list and vm_name_list list
      ansible.builtin.set_fact:
        dns_entry: "{{ ip_address_list | zip(vm_name_list) | map('join', ' ') | list }}"

    - name: Add DNS record(s) to Pihole (from project)
      ansible.builtin.lineinfile:
        backup: true
        # path: /etc/pihole/custom.list
        path: /var/tmp/pihole/custom.list
        line: "{{ dns_entry_item }}.{{ dns_suffix_list[0] }}"
        state: present
      loop: "{{ dns_entry }}"
      loop_control:
        loop_var: dns_entry_item
      delegate_to: localhost
  when: ip_address_list is defined

- name: Add DNS record to Pihole
  ansible.builtin.lineinfile:
    backup: true
    path: /var/tmp/pihole/custom.list
    regexp: "{{ customhost }}"
    line: "{{ customip }} {{ customhost }}"
    state: present
  delegate_to: localhost
  when: customhost is defined

- name: Copy custom.list to main pihole
  ansible.builtin.copy:
    src: /var/tmp/pihole/custom.list
    dest: /opt/pihole/etc-pihole/custom.list
    mode: '0644'
  notify: Restart pihole-FTL

- name: Clean up tmp files
  ansible.builtin.file:
    path: /var/tmp/pihole
    state: absent
  delegate_to: localhost

- name: Clean up key
  ansible.builtin.file:
    path: /var/tmp/ssh-key-git.key
    state: absent
  delegate_to: localhost