- name: Restart pihole container
  community.docker.docker_container:
    name: pihole
    image: pihole/pihole:{{ ver }}
    env:
      TZ: 'America/Los_Angeles'
      WEBPASSWORD: "{{ lookup('hashi_vault', 'secret=secret/data/ssh/eingram:ssh_password') }}"
      DNSMASQ_LISTENING: all
    volumes:
      - /opt/pihole/etc-pihole:/etc/pihole
      - /opt/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    restart_policy: always
    state: started
    restart: true
